/**
 * Artifact Renderer Components
 * ============================
 * Renders different artifact types generated by the AG-UI backend:
 * - Task List (Antigravity-style progress tracking)
 * - Docking Results (binding energy charts)
 * - Interaction Maps (protein-ligand contacts)
 * - Cluster Visualizations (t-SNE scatter plots)
 * - 3D Structures (links to Mol* viewer)
 * - Google Docs-style comments (Antigravity "trust bridge")
 */

import React, { useState, useEffect } from 'react';
import {
  CheckCircle2,
  Circle,
  Loader2,
  ListTodo,
  Activity,
  Dna,
  Server,
  BookOpen,
  MessageCircle,
  Send,
  Check,
  X
} from 'lucide-react';
import {
  Artifact,
  ArtifactType,
  TaskListContent,
  DockingResultContent,
  ProtocolContent,
  ExperimentMatrixContent,
  DiscoveryReportContent,
  PublicationFigureContent,
} from '../services/aguiService';

// =============================================================================
// Task List Artifact (Antigravity-style)
// =============================================================================

interface TaskListProps {
  content: TaskListContent;
}

export const TaskListArtifact: React.FC<TaskListProps> = ({ content }) => {
  const { tasks, completed, total } = content;
  const progress = total > 0 ? (completed / total) * 100 : 0;

  return (
    <div className="bg-am-secondary rounded-lg border border-am-border overflow-hidden">
      {/* Header */}
      <div className="bg-am-tertiary px-4 py-3 border-b border-am-border flex items-center justify-between">
        <h3 className="text-sm font-semibold text-am-text-primary flex items-center gap-2">
          <ListTodo className="w-4 h-4 text-am-accent" />
          Research Protocol
        </h3>
        <div className="flex items-center gap-2">
           <span className="text-xs font-mono text-am-text-muted bg-am-primary px-2 py-0.5 rounded border border-am-border">
             {completed}/{total} Steps
           </span>
        </div>
      </div>

      {/* Progress Bar */}
      <div className="h-1 bg-am-primary w-full">
        <div
          className="h-full bg-am-accent transition-all duration-500 ease-out"
          style={{ width: `${progress}%` }}
        />
      </div>

      {/* Tasks */}
      <div className="divide-y divide-am-border/50">
        {tasks.map((task, idx) => (
          <div
            key={idx}
            className={`px-4 py-3 flex items-start gap-3 transition-colors ${
              task.status === 'in_progress' ? 'bg-am-accent/10' : 'bg-am-secondary'
            }`}
          >
            {/* Icon */}
            <div className="mt-0.5 flex-shrink-0">
              {task.status === 'completed' ? (
                <CheckCircle2 className="w-4 h-4 text-green-400" />
              ) : task.status === 'in_progress' ? (
                <Loader2 className="w-4 h-4 text-am-accent animate-spin" />
              ) : (
                <Circle className="w-4 h-4 text-am-text-muted" />
              )}
            </div>

            {/* Content */}
            <div className="flex-1 min-w-0">
              <p className={`text-sm font-medium ${
                task.status === 'completed' ? 'text-am-text-muted' :
                task.status === 'in_progress' ? 'text-am-accent' : 'text-am-text-secondary'
              }`}>
                {task.name}
              </p>
              <div className="mt-1 flex items-center gap-2">
                <span className="text-[10px] text-am-text-muted font-mono uppercase tracking-wider">
                  {(task.tool || 'processing').replace(/_/g, ' ')}
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// =============================================================================
// Docking Results Artifact
// =============================================================================

interface DockingResultProps {
  content: DockingResultContent;
}

export const DockingResultArtifact: React.FC<DockingResultProps> = ({ content }) => {
  const { binding_scores, ensemble_average, visualization } = content;
  const bestScore = Math.min(...binding_scores);
  const worstScore = Math.max(...binding_scores);

  // Determine binding strength
  const getBindingStrength = (score: number) => {
    if (score <= -7) return { label: 'Strong', color: 'text-green-400', bg: 'bg-green-500' };
    if (score <= -5) return { label: 'Moderate', color: 'text-yellow-400', bg: 'bg-yellow-500' };
    return { label: 'Weak', color: 'text-red-400', bg: 'bg-red-500' };
  };

  const strength = getBindingStrength(bestScore);

  return (
    <div className="bg-slate-900 rounded-xl p-4 border border-slate-800">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-semibold text-slate-200 flex items-center gap-2">
          <svg className="w-4 h-4 text-purple-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M12 2L2 7l10 5 10-5-10-5z" />
            <path d="M2 17l10 5 10-5" />
            <path d="M2 12l10 5 10-5" />
          </svg>
          Docking Results
        </h3>
        <span className={`text-xs px-2 py-0.5 rounded ${strength.bg} text-black font-medium`}>
          {strength.label} Binding
        </span>
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-3 gap-3 mb-4">
        <div className="bg-slate-800/50 rounded-lg p-3 text-center">
          <div className={`text-lg font-bold ${strength.color}`}>
            {bestScore.toFixed(1)}
          </div>
          <div className="text-[10px] text-slate-500 uppercase">Best (kcal/mol)</div>
        </div>
        <div className="bg-slate-800/50 rounded-lg p-3 text-center">
          <div className="text-lg font-bold text-slate-300">
            {ensemble_average?.toFixed(1) || '-'}
          </div>
          <div className="text-[10px] text-slate-500 uppercase">Ensemble Avg</div>
        </div>
        <div className="bg-slate-800/50 rounded-lg p-3 text-center">
          <div className="text-lg font-bold text-slate-400">
            {binding_scores.length}
          </div>
          <div className="text-[10px] text-slate-500 uppercase">Clusters</div>
        </div>
      </div>

      {/* Bar Chart */}
      <div className="space-y-1.5">
        <div className="text-xs text-slate-500 mb-2">Binding Energy per Cluster</div>
        {binding_scores.map((score, idx) => {
          const width = ((score - worstScore) / (bestScore - worstScore)) * 100;
          const barStrength = getBindingStrength(score);

          return (
            <div key={idx} className="flex items-center gap-2">
              <span className="text-[10px] text-slate-500 w-8">C{idx + 1}</span>
              <div className="flex-1 h-4 bg-slate-800 rounded overflow-hidden">
                <div
                  className={`h-full ${barStrength.bg} opacity-80 transition-all duration-500`}
                  style={{ width: `${Math.max(5, width)}%` }}
                />
              </div>
              <span className={`text-xs font-mono w-14 text-right ${barStrength.color}`}>
                {score.toFixed(1)}
              </span>
            </div>
          );
        })}
      </div>

      {/* Threshold Legend */}
      {visualization?.threshold_lines && (
        <div className="mt-4 pt-3 border-t border-slate-800 flex items-center gap-4">
          {visualization.threshold_lines.map((line, idx) => (
            <div key={idx} className="flex items-center gap-1.5 text-[10px]">
              <span
                className="w-2 h-2 rounded"
                style={{ backgroundColor: line.color }}
              />
              <span className="text-slate-500">{line.label}</span>
              <span className="text-slate-400">({line.value})</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// =============================================================================
// Interaction Map Artifact
// =============================================================================

interface InteractionMapContent {
  interactions: {
    residues?: string[];
    h_bonds?: number;
    hydrophobic?: number;
    aromatic?: number;
    ionic?: number;
  };
  visualization: {
    type: string;
    residues: string[];
    interaction_types: string[];
  };
}

interface InteractionMapProps {
  content: InteractionMapContent;
}

export const InteractionMapArtifact: React.FC<InteractionMapProps> = ({ content }) => {
  const { interactions } = content;

  const interactionTypes = [
    { key: 'h_bonds', label: 'H-Bonds', color: 'bg-blue-500', icon: '⚡' },
    { key: 'hydrophobic', label: 'Hydrophobic', color: 'bg-yellow-500', icon: '🔶' },
    { key: 'aromatic', label: 'π-Stacking', color: 'bg-purple-500', icon: '⭕' },
    { key: 'ionic', label: 'Ionic', color: 'bg-red-500', icon: '±' },
  ];

  return (
    <div className="bg-slate-900 rounded-xl p-4 border border-slate-800">
      {/* Header */}
      <div className="flex items-center gap-2 mb-4">
        <svg className="w-4 h-4 text-cyan-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <circle cx="12" cy="12" r="10" />
          <path d="M12 16v-4" />
          <path d="M12 8h.01" />
        </svg>
        <h3 className="text-sm font-semibold text-slate-200">Interaction Analysis</h3>
      </div>

      {/* Interaction Counts */}
      <div className="grid grid-cols-2 gap-2">
        {interactionTypes.map(type => {
          const count = (interactions as any)[type.key] || 0;
          return (
            <div
              key={type.key}
              className="flex items-center gap-3 p-3 bg-slate-800/50 rounded-lg"
            >
              <div className={`w-8 h-8 ${type.color} rounded-lg flex items-center justify-center text-white text-sm`}>
                {type.icon}
              </div>
              <div>
                <div className="text-lg font-bold text-slate-200">{count}</div>
                <div className="text-[10px] text-slate-500">{type.label}</div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Residues List */}
      {interactions.residues && interactions.residues.length > 0 && (
        <div className="mt-4 pt-3 border-t border-slate-800">
          <div className="text-xs text-slate-500 mb-2">Interacting Residues</div>
          <div className="flex flex-wrap gap-1">
            {interactions.residues.map((res, idx) => (
              <span
                key={idx}
                className="px-2 py-0.5 bg-slate-800 rounded text-xs text-slate-300 font-mono"
              >
                {res}
              </span>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

// =============================================================================
// Literature Artifact (Multimodal Evidence)
// =============================================================================

interface LiteratureContent {
  title: string;
  pmcid: string;
  figures: string[]; // URLs
  summary: string;
}

export const LiteratureArtifact: React.FC<{ content: LiteratureContent }> = ({ content }) => {
  return (
    <div className="bg-am-secondary border border-am-border rounded-xl p-4">
      <div className="flex items-center gap-2 mb-3 border-b border-am-border pb-2">
        <div className="p-1 bg-indigo-500/20 rounded">
          <BookOpen className="w-4 h-4 text-indigo-400" />
        </div>
        <div className="flex-1 min-w-0">
          <h3 className="text-sm font-semibold text-am-text-primary truncate">{content.title}</h3>
          <p className="text-xs text-am-text-muted font-mono">{content.pmcid}</p>
        </div>
      </div>

      <p className="text-xs text-am-text-secondary mb-4 leading-relaxed">{content.summary}</p>

      <div className="grid grid-cols-2 gap-2">
        {content.figures.map((url, idx) => (
          <div key={idx} className="relative group rounded-lg overflow-hidden border border-am-border bg-am-tertiary aspect-video">
            <img
              src={url}
              alt={`Figure ${idx + 1}`}
              className="w-full h-full object-cover transition-transform group-hover:scale-105"
            />
            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center opacity-0 group-hover:opacity-100">
              <span className="bg-am-secondary text-am-text-primary text-[10px] font-bold px-2 py-1 rounded shadow-sm">
                Figure {idx + 1}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// =============================================================================
// Cluster Visualization Artifact
// =============================================================================

interface ClusterContent {
  n_clusters: number;
  populations: number[];
  representatives: number[];
  tsne_coordinates?: Array<[number, number]>;
}

interface ClusterVisualizationProps {
  content: ClusterContent;
}

export const ClusterVisualizationArtifact: React.FC<ClusterVisualizationProps> = ({ content }) => {
  const { n_clusters, populations, representatives } = content;
  const totalPopulation = populations.reduce((a, b) => a + b, 0);
  const maxPopulation = Math.max(...populations);

  return (
    <div className="bg-slate-900 rounded-xl p-4 border border-slate-800">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-semibold text-slate-200 flex items-center gap-2">
          <svg className="w-4 h-4 text-orange-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <circle cx="12" cy="12" r="3" />
            <circle cx="19" cy="12" r="2" />
            <circle cx="5" cy="12" r="2" />
            <circle cx="12" cy="5" r="2" />
            <circle cx="12" cy="19" r="2" />
          </svg>
          Conformational Clusters
        </h3>
        <span className="text-xs text-slate-500">{n_clusters} clusters</span>
      </div>

      {/* Summary */}
      <div className="grid grid-cols-2 gap-3 mb-4">
        <div className="bg-slate-800/50 rounded-lg p-3">
          <div className="text-lg font-bold text-orange-400">{totalPopulation}</div>
          <div className="text-[10px] text-slate-500 uppercase">Conformations</div>
        </div>
        <div className="bg-slate-800/50 rounded-lg p-3">
          <div className="text-lg font-bold text-slate-300">{n_clusters}</div>
          <div className="text-[10px] text-slate-500 uppercase">Representatives</div>
        </div>
      </div>

      {/* Population Distribution */}
      <div className="space-y-1.5">
        <div className="text-xs text-slate-500 mb-2">Cluster Populations</div>
        {populations.slice(0, 10).map((pop, idx) => {
          const width = (pop / maxPopulation) * 100;
          const percentage = ((pop / totalPopulation) * 100).toFixed(1);

          return (
            <div key={idx} className="flex items-center gap-2">
              <span className="text-[10px] text-slate-500 w-8">C{idx + 1}</span>
              <div className="flex-1 h-3 bg-slate-800 rounded overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-orange-500 to-amber-400 transition-all duration-300"
                  style={{ width: `${width}%` }}
                />
              </div>
              <span className="text-xs text-slate-400 w-12 text-right">{percentage}%</span>
            </div>
          );
        })}
        {populations.length > 10 && (
          <div className="text-xs text-slate-600 text-center mt-2">
            +{populations.length - 10} more clusters
          </div>
        )}
      </div>

      {/* Representative Frames */}
      <div className="mt-4 pt-3 border-t border-slate-800">
        <div className="text-xs text-slate-500 mb-2">Representative Frames</div>
        <div className="flex flex-wrap gap-1">
          {representatives.slice(0, 20).map((frame, idx) => (
            <span
              key={idx}
              className="px-2 py-0.5 bg-orange-900/30 rounded text-xs text-orange-300 font-mono"
            >
              {frame}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
};

// =============================================================================
// Markdown Artifact (Implementation Plan, Walkthrough)
// =============================================================================

interface MarkdownArtifactProps {
  content: string;
  title: string;
}

export const MarkdownArtifact: React.FC<MarkdownArtifactProps> = ({ content, title }) => {
  return (
    <div className="bg-slate-900 rounded-xl p-4 border border-slate-800">
      <div className="flex items-center gap-2 mb-3">
        <svg className="w-4 h-4 text-gray-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
          <polyline points="14 2 14 8 20 8" />
          <line x1="16" y1="13" x2="8" y2="13" />
          <line x1="16" y1="17" x2="8" y2="17" />
          <polyline points="10 9 9 9 8 9" />
        </svg>
        <h3 className="text-sm font-semibold text-slate-200">{title}</h3>
      </div>
      <div className="bg-slate-950 rounded-lg p-4 overflow-x-auto">
        <pre className="text-sm text-slate-300 font-mono whitespace-pre-wrap">{content}</pre>
      </div>
    </div>
  );
};

// =============================================================================
// Artifact Feedback Component (Google Docs-style)
// =============================================================================

const API_BASE = 'http://localhost:8002';

interface FeedbackItem {
  id: string;
  user_id: string;
  comment: string;
  resolved: boolean;
  created_at: string;
}

interface ArtifactWithFeedbackProps {
  artifact: Artifact;
  onStructureClick?: (pdbData: string) => void;
  children: React.ReactNode;
}

const ArtifactWithFeedback: React.FC<ArtifactWithFeedbackProps> = ({
  artifact,
  children
}) => {
  const [showComments, setShowComments] = useState(false);
  const [comments, setComments] = useState<FeedbackItem[]>([]);
  const [newComment, setNewComment] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Fetch existing comments
  useEffect(() => {
    const fetchComments = async () => {
      try {
        const response = await fetch(`${API_BASE}/feedback/${artifact.id}`);
        if (response.ok) {
          const data = await response.json();
          setComments(data.feedback || []);
        }
      } catch (e) {
        console.log('Failed to fetch comments:', e);
      }
    };
    if (showComments) {
      fetchComments();
    }
  }, [artifact.id, showComments]);

  const handleAddComment = async () => {
    if (!newComment.trim() || isSubmitting) return;

    setIsSubmitting(true);
    try {
      const response = await fetch(`${API_BASE}/feedback`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          artifact_id: artifact.id,
          comment: newComment.trim()
        })
      });

      if (response.ok) {
        const newFeedback = await response.json();
        setComments(prev => [...prev, newFeedback]);
        setNewComment('');
      }
    } catch (e) {
      console.error('Failed to add comment:', e);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleResolve = async (feedbackId: string) => {
    try {
      const response = await fetch(`${API_BASE}/feedback/${feedbackId}/resolve`, {
        method: 'PUT'
      });
      if (response.ok) {
        setComments(prev =>
          prev.map(c => c.id === feedbackId ? { ...c, resolved: true } : c)
        );
      }
    } catch (e) {
      console.error('Failed to resolve comment:', e);
    }
  };

  const unresolvedCount = comments.filter(c => !c.resolved).length;

  return (
    <div className="relative">
      {children}

      {/* Comment Button */}
      <div className="absolute top-2 right-2 flex items-center gap-2">
        <button
          onClick={() => setShowComments(!showComments)}
          className={`flex items-center gap-1.5 px-2 py-1 text-xs rounded-lg transition-colors ${
            showComments
              ? 'bg-am-accent text-white'
              : 'bg-am-tertiary text-am-text-secondary hover:bg-am-border'
          }`}
        >
          <MessageCircle className="w-3 h-3" />
          <span>Comments</span>
          {unresolvedCount > 0 && (
            <span className="bg-red-500 text-white text-[10px] px-1.5 rounded-full">
              {unresolvedCount}
            </span>
          )}
        </button>
      </div>

      {/* Comments Panel */}
      {showComments && (
        <div className="mt-3 pt-3 border-t border-am-border space-y-3">
          {/* Existing Comments */}
          {comments.length > 0 && (
            <div className="space-y-2">
              {comments.map(comment => (
                <div
                  key={comment.id}
                  className={`p-2 rounded-lg text-xs ${
                    comment.resolved
                      ? 'bg-am-tertiary/50 opacity-60'
                      : 'bg-am-tertiary'
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1 min-w-0">
                      <div className="font-medium text-am-text-primary mb-1">
                        {comment.user_id}
                      </div>
                      <div className="text-am-text-secondary whitespace-pre-wrap">
                        {comment.comment}
                      </div>
                      <div className="text-am-text-muted mt-1 text-[10px]">
                        {new Date(comment.created_at).toLocaleString()}
                      </div>
                    </div>
                    {!comment.resolved && (
                      <button
                        onClick={() => handleResolve(comment.id)}
                        className="flex-shrink-0 p-1 text-green-400 hover:bg-green-500/20 rounded transition-colors"
                        title="Mark as resolved"
                      >
                        <Check className="w-3 h-3" />
                      </button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* New Comment Input */}
          <div className="flex gap-2">
            <input
              type="text"
              value={newComment}
              onChange={(e) => setNewComment(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleAddComment()}
              placeholder="Add a comment..."
              className="flex-1 px-3 py-2 text-xs bg-am-secondary border border-am-border rounded-lg text-am-text-primary placeholder-am-text-muted focus:outline-none focus:border-am-accent"
            />
            <button
              onClick={handleAddComment}
              disabled={!newComment.trim() || isSubmitting}
              className="px-3 py-2 bg-am-accent text-white text-xs rounded-lg hover:bg-am-accent-hover disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <Send className="w-3 h-3" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

// =============================================================================
// Protocol Artifact (Research Phase)
// =============================================================================

interface ProtocolProps {
  content: ProtocolContent;
}

export const ProtocolArtifact: React.FC<ProtocolProps> = ({ content }) => {
  const {
    protein_name,
    ped_id,
    n_conformations,
    binding_site_residues,
    ligands,
    visuals,
    validation_status,
    confidence_score,
    figure_urls,
    literature_results
  } = content;

  const statusColor = {
    pending: 'bg-yellow-500/20 text-yellow-400',
    validated: 'bg-green-500/20 text-green-400',
    failed: 'bg-red-500/20 text-red-400'
  }[validation_status];

  return (
    <div className="bg-slate-900 rounded-xl border border-slate-800 overflow-hidden">
      {/* Header */}
      <div className="bg-slate-800/50 px-4 py-3 border-b border-slate-800 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Dna className="w-4 h-4 text-purple-400" />
          <h3 className="text-sm font-semibold text-slate-200">Protocol: {protein_name}</h3>
        </div>
        <div className="flex items-center gap-2">
          <span className={`text-[10px] px-2 py-0.5 rounded ${statusColor}`}>
            {validation_status}
          </span>
          <span className="text-xs text-slate-400">Score: {confidence_score.toFixed(1)}</span>
        </div>
      </div>

      <div className="p-4 space-y-4">
        {/* Target Info */}
        <div className="grid grid-cols-3 gap-3">
          <div className="bg-slate-800/50 rounded-lg p-3 text-center">
            <div className="text-lg font-bold text-purple-400">{ped_id}</div>
            <div className="text-[10px] text-slate-500 uppercase">PED ID</div>
          </div>
          <div className="bg-slate-800/50 rounded-lg p-3 text-center">
            <div className="text-lg font-bold text-slate-300">{n_conformations}</div>
            <div className="text-[10px] text-slate-500 uppercase">Conformations</div>
          </div>
          <div className="bg-slate-800/50 rounded-lg p-3 text-center">
            <div className="text-lg font-bold text-cyan-400">{binding_site_residues?.length || 0}</div>
            <div className="text-[10px] text-slate-500 uppercase">Binding Site</div>
          </div>
        </div>

        {/* Binding Site Residues */}
        {binding_site_residues && binding_site_residues.length > 0 && (
          <div>
            <div className="text-xs text-slate-500 mb-2">Binding Site Residues</div>
            <div className="flex flex-wrap gap-1">
              {binding_site_residues.map((res, idx) => (
                <span key={idx} className="px-2 py-0.5 bg-cyan-900/30 rounded text-xs text-cyan-300 font-mono">
                  Y{res}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Ligands with Images */}
        {ligands && ligands.length > 0 && (
          <div>
            <div className="text-xs text-slate-500 mb-2">Ligands ({ligands.length})</div>
            <div className="grid grid-cols-2 gap-3">
              {ligands.map((lig, idx) => (
                <div key={idx} className="bg-slate-800/30 rounded-lg p-3 flex gap-3">
                  {/* Ligand 2D Image */}
                  {lig.image_base64 && (
                    <div className="w-16 h-16 flex-shrink-0 bg-white rounded overflow-hidden">
                      <img
                        src={`data:image/png;base64,${lig.image_base64}`}
                        alt={lig.name}
                        className="w-full h-full object-contain"
                      />
                    </div>
                  )}
                  <div className="flex-1 min-w-0">
                    <div className="text-sm font-medium text-slate-200">{lig.name}</div>
                    <div className="text-[10px] text-slate-500 font-mono truncate mt-1">
                      {lig.smiles?.slice(0, 30)}...
                    </div>
                    {lig.chembl_id && (
                      <div className="text-[10px] text-purple-400 mt-1">{lig.chembl_id}</div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Visual Links */}
        {visuals && (
          <div>
            <div className="text-xs text-slate-500 mb-2">Visual Resources</div>
            <div className="flex flex-wrap gap-2">
              {visuals.ped_viewer_url && (
                <a
                  href={visuals.ped_viewer_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs px-3 py-1.5 bg-purple-900/30 text-purple-300 rounded-lg hover:bg-purple-900/50 transition-colors"
                >
                  View on PED
                </a>
              )}
            </div>
          </div>
        )}

        {/* Figure URLs */}
        {figure_urls && figure_urls.length > 0 && (
          <div>
            <div className="text-xs text-slate-500 mb-2">Validation Figures</div>
            <div className="grid grid-cols-3 gap-2">
              {figure_urls.slice(0, 3).map((url, idx) => (
                <a
                  key={idx}
                  href={url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="aspect-video bg-slate-800 rounded overflow-hidden hover:ring-2 ring-purple-500 transition-all"
                >
                  <img src={url} alt={`Figure ${idx + 1}`} className="w-full h-full object-cover" />
                </a>
              ))}
            </div>
          </div>
        )}

        {/* Literature */}
        {literature_results && literature_results.length > 0 && (
          <div>
            <div className="text-xs text-slate-500 mb-2">Literature Evidence</div>
            <div className="space-y-1">
              {literature_results.slice(0, 3).map((paper, idx) => (
                <div key={idx} className="text-xs text-slate-400 flex items-center gap-2">
                  <BookOpen className="w-3 h-3 text-slate-500" />
                  <span className="truncate">{paper.title}</span>
                  {paper.pmcid && (
                    <span className="text-purple-400 font-mono flex-shrink-0">{paper.pmcid}</span>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// =============================================================================
// Experiment Matrix Artifact (Engineering Phase)
// =============================================================================

interface ExperimentMatrixProps {
  content: ExperimentMatrixContent;
}

export const ExperimentMatrixArtifact: React.FC<ExperimentMatrixProps> = ({ content }) => {
  const { ligands, n_clusters, representative_frames } = content;

  const completed = ligands.filter(l => l.status === 'completed').length;
  const running = ligands.filter(l => l.status === 'running').length;

  return (
    <div className="bg-slate-900 rounded-xl border border-slate-800 overflow-hidden">
      {/* Header */}
      <div className="bg-slate-800/50 px-4 py-3 border-b border-slate-800 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Server className="w-4 h-4 text-orange-400" />
          <h3 className="text-sm font-semibold text-slate-200">Experiment Matrix</h3>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-400">{completed}/{ligands.length} complete</span>
          {running > 0 && (
            <span className="flex items-center gap-1 text-xs text-orange-400">
              <Loader2 className="w-3 h-3 animate-spin" />
              {running} running
            </span>
          )}
        </div>
      </div>

      <div className="p-4 space-y-4">
        {/* Cluster Info */}
        <div className="grid grid-cols-2 gap-3">
          <div className="bg-slate-800/50 rounded-lg p-3 text-center">
            <div className="text-lg font-bold text-orange-400">{n_clusters}</div>
            <div className="text-[10px] text-slate-500 uppercase">Clusters</div>
          </div>
          <div className="bg-slate-800/50 rounded-lg p-3 text-center">
            <div className="text-lg font-bold text-slate-300">{representative_frames?.length || 0}</div>
            <div className="text-[10px] text-slate-500 uppercase">Representatives</div>
          </div>
        </div>

        {/* Ligand Results Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="text-slate-500 border-b border-slate-800">
                <th className="text-left py-2 px-2">Ligand</th>
                <th className="text-center py-2 px-2">Status</th>
                <th className="text-right py-2 px-2">Energy</th>
                <th className="text-center py-2 px-2">Cluster</th>
              </tr>
            </thead>
            <tbody>
              {ligands.map((lig, idx) => (
                <tr key={idx} className="border-b border-slate-800/50">
                  <td className="py-2 px-2 text-slate-300">{lig.name}</td>
                  <td className="py-2 px-2 text-center">
                    {lig.status === 'completed' && <CheckCircle2 className="w-4 h-4 text-green-400 mx-auto" />}
                    {lig.status === 'running' && <Loader2 className="w-4 h-4 text-orange-400 mx-auto animate-spin" />}
                    {lig.status === 'queued' && <Circle className="w-4 h-4 text-slate-500 mx-auto" />}
                    {lig.status === 'failed' && <X className="w-4 h-4 text-red-400 mx-auto" />}
                  </td>
                  <td className="py-2 px-2 text-right font-mono text-green-400">
                    {lig.best_energy ? `${lig.best_energy.toFixed(1)}` : '-'}
                  </td>
                  <td className="py-2 px-2 text-center text-slate-400">
                    {lig.best_cluster !== undefined ? `C${lig.best_cluster + 1}` : '-'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

// =============================================================================
// Discovery Report Artifact (Evolution Phase)
// =============================================================================

interface DiscoveryReportProps {
  content: DiscoveryReportContent;
}

export const DiscoveryReportArtifact: React.FC<DiscoveryReportProps> = ({ content }) => {
  const { title, executive_summary, energy_stats, ucb_rankings, sar_insights, recommendations } = content;

  return (
    <div className="bg-slate-900 rounded-xl border border-slate-800 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-900/50 to-slate-800/50 px-4 py-3 border-b border-slate-800">
        <h3 className="text-sm font-semibold text-slate-200 flex items-center gap-2">
          <Activity className="w-4 h-4 text-purple-400" />
          {title || 'Discovery Report'}
        </h3>
      </div>

      <div className="p-4 space-y-4">
        {/* Executive Summary */}
        {executive_summary && (
          <div className="p-3 bg-slate-800/50 rounded-lg">
            <div className="text-xs text-slate-500 uppercase mb-1">Executive Summary</div>
            <p className="text-sm text-slate-300">{executive_summary}</p>
          </div>
        )}

        {/* Stats */}
        {energy_stats && (
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-slate-800/50 rounded-lg p-3 text-center">
              <div className="text-lg font-bold text-green-400">{energy_stats.n_completed}</div>
              <div className="text-[10px] text-slate-500 uppercase">Completed</div>
            </div>
            <div className="bg-slate-800/50 rounded-lg p-3 text-center">
              <div className="text-lg font-bold text-cyan-400">{energy_stats.best_energy?.toFixed(1)}</div>
              <div className="text-[10px] text-slate-500 uppercase">Best (kcal/mol)</div>
            </div>
            <div className="bg-slate-800/50 rounded-lg p-3 text-center">
              <div className="text-lg font-bold text-purple-400">{energy_stats.n_drug_like}</div>
              <div className="text-[10px] text-slate-500 uppercase">Drug-like</div>
            </div>
          </div>
        )}

        {/* UCB Rankings */}
        {ucb_rankings && ucb_rankings.length > 0 && (
          <div>
            <div className="text-xs text-slate-500 uppercase mb-2">Top Ligands (UCB Ranking)</div>
            <div className="space-y-1">
              {ucb_rankings.slice(0, 5).map((r, i) => (
                <div key={i} className="flex items-center justify-between p-2 bg-slate-800/30 rounded">
                  <span className="text-sm text-slate-300">{i + 1}. {r.ligand_name}</span>
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-slate-400">{r.best_energy?.toFixed(1)} kcal/mol</span>
                    {r.drug_like && (
                      <span className="text-[10px] bg-green-500/20 text-green-400 px-1.5 py-0.5 rounded">Drug-like</span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* SAR Insights */}
        {sar_insights && sar_insights.length > 0 && (
          <div>
            <div className="text-xs text-slate-500 uppercase mb-2">SAR Insights</div>
            <div className="space-y-2">
              {sar_insights.map((insight, i) => (
                <div key={i} className="p-3 bg-purple-900/20 border border-purple-800/30 rounded-lg">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-[10px] px-1.5 py-0.5 bg-purple-500/20 text-purple-300 rounded">
                      {insight.pattern_type?.replace(/_/g, ' ')}
                    </span>
                    <span className="text-[10px] text-slate-500">
                      {Math.round(insight.confidence * 100)}% confidence
                    </span>
                  </div>
                  <div className="text-sm font-medium text-slate-200">{insight.title}</div>
                  <div className="text-xs text-slate-400 mt-1">{insight.description}</div>
                  {insight.recommendation && (
                    <div className="text-xs text-purple-300 mt-2 p-2 bg-purple-900/30 rounded">
                      {insight.recommendation}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Recommendations */}
        {recommendations && recommendations.length > 0 && (
          <div>
            <div className="text-xs text-slate-500 uppercase mb-2">Next Steps</div>
            {recommendations.map((rec, i) => (
              <div key={i} className="flex items-start gap-2 p-2 bg-slate-800/30 rounded mb-1">
                <span className={`text-[10px] px-1.5 py-0.5 rounded flex-shrink-0 ${
                  rec.priority === 'high' ? 'bg-red-500/20 text-red-400' :
                  rec.priority === 'medium' ? 'bg-yellow-500/20 text-yellow-400' :
                  'bg-slate-500/20 text-slate-400'
                }`}>{rec.priority}</span>
                <span className="text-xs text-slate-300">{rec.recommendation}</span>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

// =============================================================================
// Publication Figure Artifact (Evolution Phase - Gemini Code Execution)
// =============================================================================

interface PublicationFigureProps {
  content: PublicationFigureContent;
}

export const PublicationFigureArtifact: React.FC<PublicationFigureProps> = ({ content }) => {
  const { title, figure_type, image_base64, caption, annotations } = content;

  const figureTypeLabels: Record<string, string> = {
    interaction_map: 'Interaction Map',
    binding_energy: 'Binding Energy',
    cluster_analysis: 'Cluster Analysis',
    sar_plot: 'SAR Analysis'
  };

  return (
    <div className="bg-slate-900 rounded-xl border border-slate-800 overflow-hidden">
      {/* Header */}
      <div className="bg-slate-800/50 px-4 py-3 border-b border-slate-800 flex items-center justify-between">
        <h3 className="text-sm font-semibold text-slate-200">{title}</h3>
        <span className="text-[10px] px-2 py-0.5 bg-purple-500/20 text-purple-300 rounded">
          {figureTypeLabels[figure_type] || figure_type}
        </span>
      </div>

      {/* Figure */}
      <div className="p-4">
        {image_base64 && (
          <div className="relative bg-white rounded-lg overflow-hidden">
            <img
              src={`data:image/png;base64,${image_base64}`}
              alt={title}
              className="w-full h-auto"
            />
            {/* Annotations overlay */}
            {annotations && annotations.map((ann, idx) => (
              <div
                key={idx}
                className="absolute text-xs bg-black/70 text-white px-1.5 py-0.5 rounded"
                style={{ left: `${ann.x}%`, top: `${ann.y}%`, transform: 'translate(-50%, -50%)' }}
              >
                {ann.text}
              </div>
            ))}
          </div>
        )}

        {/* Caption */}
        {caption && (
          <div className="mt-3 text-xs text-slate-400 italic">
            <strong className="text-slate-300">Figure:</strong> {caption}
          </div>
        )}
      </div>
    </div>
  );
};

// =============================================================================
// Main Artifact Renderer
// =============================================================================

interface ArtifactRendererProps {
  artifact: Artifact;
  onStructureClick?: (pdbData: string) => void;
  enableFeedback?: boolean;
}

export const ArtifactRenderer: React.FC<ArtifactRendererProps> = ({
  artifact,
  onStructureClick,
  enableFeedback = true,
}) => {
  // Guard against malformed artifacts
  if (!artifact || !artifact.type) {
    console.warn('ArtifactRenderer: Invalid artifact', artifact);
    return null;
  }

  const renderArtifact = () => {
    try {
    switch (artifact.type) {
      case ArtifactType.TASK_LIST:
        return <TaskListArtifact content={artifact.content as TaskListContent} />;

      case ArtifactType.DOCKING_RESULT:
        return <DockingResultArtifact content={artifact.content as DockingResultContent} />;

      case ArtifactType.INTERACTION_MAP:
        return <InteractionMapArtifact content={artifact.content as InteractionMapContent} />;

      case ArtifactType.LITERATURE_RESULT:
        return <LiteratureArtifact content={artifact.content as LiteratureContent} />;

      case ArtifactType.CLUSTER_VISUALIZATION:
        return <ClusterVisualizationArtifact content={artifact.content as ClusterContent} />;

      case ArtifactType.IMPLEMENTATION_PLAN:
        return <MarkdownArtifact content={artifact.content as string} title="Implementation Plan" />;

      case ArtifactType.WALKTHROUGH:
        return <MarkdownArtifact content={artifact.content as string} title="Walkthrough" />;

      case ArtifactType.STRUCTURE_3D:
        // Handler to open interactive HTML viewer in new window
        const openHtmlViewer = () => {
          const htmlContent = artifact.content.html_viewer;
          if (htmlContent) {
            const newWindow = window.open('', '_blank', 'width=900,height=700');
            if (newWindow) {
              newWindow.document.write(htmlContent);
              newWindow.document.close();
            }
          }
        };

        return (
          <div className="bg-slate-900 rounded-xl p-4 border border-slate-800">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-slate-200 flex items-center gap-2">
                <svg className="w-4 h-4 text-green-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M12 2L2 7l10 5 10-5-10-5z" />
                  <path d="M2 17l10 5 10-5" />
                  <path d="M2 12l10 5 10-5" />
                </svg>
                3D Structure
              </h3>
              <div className="flex gap-2">
                {/* Interactive py3Dmol viewer (opens in new window) */}
                {artifact.content.html_viewer && (
                  <button
                    onClick={openHtmlViewer}
                    className="text-xs px-3 py-1 bg-cyan-500 hover:bg-cyan-600 text-white rounded transition-colors"
                  >
                    Open Interactive
                  </button>
                )}
                {/* Molstar viewer (inline) */}
                {onStructureClick && artifact.content.pdb_data && (
                  <button
                    onClick={() => onStructureClick(artifact.content.pdb_data)}
                    className="text-xs px-3 py-1 bg-green-500 hover:bg-green-600 text-white rounded transition-colors"
                  >
                    View in Molstar
                  </button>
                )}
              </div>
            </div>
            <div className="grid grid-cols-2 gap-2 text-xs">
              {artifact.content.metadata?.ped_id && (
                <div className="bg-slate-800/50 rounded p-2">
                  <span className="text-slate-500">PED ID:</span>
                  <span className="ml-2 text-slate-300 font-mono">{artifact.content.metadata.ped_id}</span>
                </div>
              )}
              {artifact.content.metadata?.n_conformations && (
                <div className="bg-slate-800/50 rounded p-2">
                  <span className="text-slate-500">Conformations:</span>
                  <span className="ml-2 text-slate-300">{artifact.content.metadata.n_conformations}</span>
                </div>
              )}
              {artifact.content.ligand_name && (
                <div className="bg-slate-800/50 rounded p-2">
                  <span className="text-slate-500">Ligand:</span>
                  <span className="ml-2 text-cyan-300">{artifact.content.ligand_name}</span>
                </div>
              )}
              {artifact.content.n_frames && (
                <div className="bg-slate-800/50 rounded p-2">
                  <span className="text-slate-500">Frames:</span>
                  <span className="ml-2 text-slate-300">{artifact.content.n_frames}</span>
                </div>
              )}
            </div>
          </div>
        );

      case ArtifactType.PROTOCOL:
        return <ProtocolArtifact content={artifact.content as ProtocolContent} />;

      case ArtifactType.EXPERIMENT_MATRIX:
        return <ExperimentMatrixArtifact content={artifact.content as ExperimentMatrixContent} />;

      case ArtifactType.DISCOVERY_REPORT:
        return <DiscoveryReportArtifact content={artifact.content as DiscoveryReportContent} />;

      case ArtifactType.PUBLICATION_FIGURE:
        return <PublicationFigureArtifact content={artifact.content as PublicationFigureContent} />;

      default:
        return (
          <div className="bg-slate-900 rounded-xl p-4 border border-slate-800">
            <pre className="text-xs text-slate-400 overflow-auto">
              {JSON.stringify(artifact.content, null, 2)}
            </pre>
          </div>
        );
    }
    } catch (e) {
      console.error('Error rendering artifact:', artifact.type, e);
      return (
        <div className="bg-red-900/20 rounded-xl p-4 border border-red-800">
          <div className="text-red-400 text-sm">Error rendering artifact</div>
          <div className="text-red-300 text-xs mt-1">{String(e)}</div>
        </div>
      );
    }
  };

  // Wrap with feedback if enabled
  if (enableFeedback) {
    return (
      <ArtifactWithFeedback artifact={artifact} onStructureClick={onStructureClick}>
        {renderArtifact()}
      </ArtifactWithFeedback>
    );
  }

  return renderArtifact();
};

export default ArtifactRenderer;
