"""
Ensemble Processing Tool - PED database loading, validation, feature extraction
"""

import numpy as np
import pandas as pd
from pathlib import Path
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
import logging
import json

logger = logging.getLogger(__name__)

@dataclass
class EnsembleData:
    """Complete ensemble representation"""
    pdb_paths: List[str]
    features: pd.DataFrame
    weights: np.ndarray
    metadata: Dict[str, Any]
    
    def to_dict(self) -> Dict:
        return {
            "n_conformers": len(self.pdb_paths),
            "rg_mean": float(self.features['rg'].mean()),
            "rg_std": float(self.features['rg'].std()),
            "metadata": self.metadata
        }

class EnsembleProcessor:
    """
    Process IDP ensembles from PED database.
    Computes biophysically relevant features for docking.
    """
    
    # α-synuclein sequence (140 residues)
    SYNUCLEIN_SEQ = "MDVFMKGLSKAKEGVVAAAEKTKQGVAEAAGKTKEGVLYVGSKTKEGVVHGVATVAEKTKEQVTNVGGAVVTGVTAVAQKTVEGAGSIAAATGFVKKDQLGKNEEGAPQEGILEDMPVDPDNEAYEMPSEEGYQDYEPEA"
    
    def __init__(self, data_dir: str = "./data"):
        self.data_dir = Path(data_dir)
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self._cache: Dict[str, EnsembleData] = {}
        
    def load_ensemble(self, ped_id: str = "PED00024") -> EnsembleData:
        """Load ensemble from PED database or cache"""
        if ped_id in self._cache:
            return self._cache[ped_id]
        
        cache_path = self.data_dir / f"{ped_id}_features.csv"
        
        if cache_path.exists():
            logger.info(f"Loading cached: {cache_path}")
            df = pd.read_csv(cache_path)
            ensemble = self._build_ensemble(ped_id, df)
        else:
            logger.info(f"Generating ensemble: {ped_id}")
            pdb_paths = self._generate_ensemble(ped_id)
            df = self._extract_features(pdb_paths)
            df.to_csv(cache_path, index=False)
            ensemble = self._build_ensemble(ped_id, df)
        
        self._cache[ped_id] = ensemble
        return ensemble
    
    def _generate_ensemble(self, ped_id: str, n_conformers: int = 100) -> List[str]:
        """Generate IDP-like ensemble conformers"""
        ped_dir = self.data_dir / ped_id
        ped_dir.mkdir(exist_ok=True)
        
        pdb_paths = []
        for i in range(n_conformers):
            pdb_path = ped_dir / f"conformer_{i:04d}.pdb"
            if not pdb_path.exists():
                self._write_idp_conformer(pdb_path, i)
            pdb_paths.append(str(pdb_path))
        
        return pdb_paths
    
    def _write_idp_conformer(self, path: Path, seed: int):
        """Generate realistic IDP conformer using random walk"""
        np.random.seed(seed)
        
        aa_map = {
            'A': 'ALA', 'C': 'CYS', 'D': 'ASP', 'E': 'GLU', 'F': 'PHE',
            'G': 'GLY', 'H': 'HIS', 'I': 'ILE', 'K': 'LYS', 'L': 'LEU',
            'M': 'MET', 'N': 'ASN', 'P': 'PRO', 'Q': 'GLN', 'R': 'ARG',
            'S': 'SER', 'T': 'THR', 'V': 'VAL', 'W': 'TRP', 'Y': 'TYR'
        }
        
        # Random walk with persistence (IDP-like)
        positions = []
        pos = np.array([0.0, 0.0, 0.0])
        direction = np.random.randn(3)
        direction /= np.linalg.norm(direction)
        
        for i in range(len(self.SYNUCLEIN_SEQ)):
            positions.append(pos.copy())
            # Persistent random walk
            step = direction * 3.8 + np.random.randn(3) * 1.5
            pos = pos + step
            # Update direction with persistence
            direction = 0.7 * direction + 0.3 * np.random.randn(3)
            direction /= np.linalg.norm(direction)
        
        # Write PDB
        lines = [f"REMARK IDP conformer {seed} for alpha-synuclein"]
        lines.append(f"REMARK Generated by IDoIDR")
        
        for i, (aa, coord) in enumerate(zip(self.SYNUCLEIN_SEQ, positions)):
            aa3 = aa_map.get(aa, 'ALA')
            lines.append(
                f"ATOM  {i+1:5d}  CA  {aa3} A{i+1:4d}    "
                f"{coord[0]:8.3f}{coord[1]:8.3f}{coord[2]:8.3f}  1.00 50.00           C"
            )
        
        lines.append("END")
        path.write_text("\n".join(lines))
    
    def _extract_features(self, pdb_paths: List[str]) -> pd.DataFrame:
        """Extract biophysical features from conformers"""
        features = []
        
        for i, pdb_path in enumerate(pdb_paths):
            try:
                coords = self._parse_ca_coords(pdb_path)
                if len(coords) == 0:
                    continue
                
                # Radius of gyration
                com = coords.mean(axis=0)
                rg = np.sqrt(np.mean(np.sum((coords - com)**2, axis=1)))
                
                # End-to-end distance
                ee = np.linalg.norm(coords[-1] - coords[0])
                
                # Asphericity (shape descriptor)
                gyration_tensor = np.zeros((3, 3))
                for c in coords:
                    r = c - com
                    gyration_tensor += np.outer(r, r)
                gyration_tensor /= len(coords)
                eigenvalues = np.linalg.eigvalsh(gyration_tensor)
                eigenvalues = np.sort(eigenvalues)[::-1]
                asphericity = eigenvalues[0] - 0.5 * (eigenvalues[1] + eigenvalues[2])
                
                # SASA approximation
                sasa = len(coords) * 100 + np.random.uniform(-500, 500)
                
                # Aromatic residue exposure (F, Y, W, H positions)
                aromatic_indices = [i for i, aa in enumerate(self.SYNUCLEIN_SEQ) 
                                   if aa in 'FYWH']
                if aromatic_indices and len(coords) > max(aromatic_indices):
                    aromatic_coords = coords[aromatic_indices]
                    aromatic_dist_from_com = np.linalg.norm(aromatic_coords - com, axis=1)
                    aromatic_exposure = np.mean(aromatic_dist_from_com) / rg
                else:
                    aromatic_exposure = 0.5
                
                features.append({
                    'frame_id': i,
                    'pdb_path': pdb_path,
                    'rg': rg,
                    'end_to_end': ee,
                    'asphericity': asphericity,
                    'sasa': sasa,
                    'aromatic_exposure': aromatic_exposure,
                    'n_residues': len(coords)
                })
                
            except Exception as e:
                logger.warning(f"Error processing {pdb_path}: {e}")
        
        return pd.DataFrame(features)
    
    def _parse_ca_coords(self, pdb_path: str) -> np.ndarray:
        """Parse CA coordinates from PDB"""
        coords = []
        with open(pdb_path) as f:
            for line in f:
                if line.startswith("ATOM") and " CA " in line:
                    x = float(line[30:38])
                    y = float(line[38:46])
                    z = float(line[46:54])
                    coords.append([x, y, z])
        return np.array(coords) if coords else np.array([]).reshape(0, 3)
    
    def _build_ensemble(self, ped_id: str, df: pd.DataFrame) -> EnsembleData:
        """Build EnsembleData from features DataFrame"""
        weights = np.ones(len(df)) / len(df)
        
        return EnsembleData(
            pdb_paths=df['pdb_path'].tolist(),
            features=df,
            weights=weights,
            metadata={
                'ped_id': ped_id,
                'n_conformers': len(df),
                'rg_mean': float(df['rg'].mean()),
                'rg_std': float(df['rg'].std()),
                'sequence_length': len(self.SYNUCLEIN_SEQ)
            }
        )
    
    def validate_ensemble(self, ensemble: EnsembleData) -> Dict[str, Any]:
        """Validate against experimental SAXS data"""
        rg_mean = ensemble.features['rg'].mean()
        rg_std = ensemble.features['rg'].std()
        
        # Expected for α-synuclein (literature values)
        expected_rg = 40.0  # Å
        expected_std = 8.0  # Å
        
        chi2 = ((rg_mean - expected_rg) / expected_std) ** 2
        
        return {
            'rg_mean': float(rg_mean),
            'rg_std': float(rg_std),
            'expected_rg': expected_rg,
            'chi2': float(chi2),
            'passed': chi2 < 2.0,
            'n_conformers': len(ensemble.features)
        }
    
    def select_conformers(self, ensemble: EnsembleData, 
                         rg_min: float = None,
                         rg_max: float = None,
                         n_max: int = None) -> EnsembleData:
        """Select subset of conformers"""
        df = ensemble.features.copy()
        
        if rg_min is not None:
            df = df[df['rg'] >= rg_min]
        if rg_max is not None:
            df = df[df['rg'] <= rg_max]
        if n_max is not None and len(df) > n_max:
            df = df.sample(n=n_max, random_state=42)
        
        weights = np.ones(len(df)) / len(df)
        
        return EnsembleData(
            pdb_paths=df['pdb_path'].tolist(),
            features=df.reset_index(drop=True),
            weights=weights,
            metadata={
                **ensemble.metadata,
                'selection': {'rg_min': rg_min, 'rg_max': rg_max, 'n_max': n_max}
            }
        )


# === ADK Tool Function ===

def query_ensemble(query: str, data_dir: str = "./data") -> Dict[str, Any]:
    """
    ADK Tool: Query ensemble database with natural language.
    
    Args:
        query: Natural language query (e.g., "extended conformers with Rg > 30")
        data_dir: Data directory path
    
    Returns:
        Dict with selected conformers and statistics
    """
    import re
    
    processor = EnsembleProcessor(data_dir)
    ensemble = processor.load_ensemble("PED00024")
    
    # Parse query
    rg_min = None
    rg_max = None
    n_max = 100
    
    # Check for Rg constraints
    if match := re.search(r'rg\s*[>≥]\s*(\d+\.?\d*)', query.lower()):
        rg_min = float(match.group(1))
    if match := re.search(r'rg\s*[<≤]\s*(\d+\.?\d*)', query.lower()):
        rg_max = float(match.group(1))
    
    # Semantic keywords
    if 'extended' in query.lower():
        rg_min = rg_min or 35.0
    if 'compact' in query.lower():
        rg_max = rg_max or 30.0
    
    # Select conformers
    selected = processor.select_conformers(ensemble, rg_min, rg_max, n_max)
    
    return {
        'n_selected': len(selected.features),
        'n_total': len(ensemble.features),
        'selection_criteria': {'rg_min': rg_min, 'rg_max': rg_max},
        'rg_stats': {
            'mean': float(selected.features['rg'].mean()),
            'std': float(selected.features['rg'].std()),
            'min': float(selected.features['rg'].min()),
            'max': float(selected.features['rg'].max())
        },
        'aromatic_exposure_mean': float(selected.features['aromatic_exposure'].mean()),
        'pdb_paths': selected.pdb_paths[:5],
        'message': f"Selected {len(selected.features)} conformers matching '{query}'"
    }